"""
Config Builder for Amalgam

Generates config.py from parts inventory.
Separates config generation logic from wizard UI.
"""

from pathlib import Path
from dataclasses import dataclass
from typing import Optional
import sys

# Add parent to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from registry import BOARDS, EXTRUDERS, get_tier_requirements


@dataclass
class BuildConfig:
    """Complete build configuration."""
    # Tier
    tier: int
    tier_name: str

    # Build volume
    bed_x: int
    bed_y: int
    build_z: int

    # Rods
    smooth_rod_diameter: float
    threaded_rod_type: str

    # Extruder
    extruder_id: str
    extruder_mass: int
    extruder_motor: str

    # Board
    board_ids: list[str]
    total_drivers: int

    # Z config
    z_configuration: str  # "triple" or "belt"
    has_canbus: bool


def generate_config(config: BuildConfig) -> str:
    """
    Generate config.py content from BuildConfig.

    Args:
        config: BuildConfig object with all settings

    Returns:
        String content for config.py
    """

    boards = [BOARDS[bid] for bid in config.board_ids if bid in BOARDS]
    primary_board = boards[0] if boards else None
    primary_board_id = primary_board.id if primary_board else "UNKNOWN"

    content = f'''"""
Amalgam Configuration
Generated by Amalgam Build System

Tier: {config.tier} ({config.tier_name})
"""

# =============================================================================
# 1. BUILD VOLUME
# =============================================================================

BUILD_VOLUME = {{
    "x": {config.bed_x},
    "y": {config.bed_y},
    "z": {config.build_z},
}}

# =============================================================================
# 2. FRAME SKELETON (M10 Rods)
# =============================================================================

# Threaded rods (frame structure)
M10_NOMINAL_DIA = 10.0
LUMPY_FACTOR = 0.5  # Tolerance for rod variation (0.2 zinc, 0.5+ galvanized)
M10_FIT_DIA = M10_NOMINAL_DIA + LUMPY_FACTOR

# Smooth rods (linear motion)
SMOOTH_ROD_DIA = {config.smooth_rod_diameter}
SMOOTH_ROD_FIT = SMOOTH_ROD_DIA + 0.1  # Tight fit for linear bearings

# =============================================================================
# 3. BED CONFIGURATION
# =============================================================================

BED_SIZE_X = {config.bed_x}
BED_SIZE_Y = {config.bed_y}

# =============================================================================
# 4. EXTRUDER
# =============================================================================

EXTRUDER_TYPE = "{config.extruder_id}"
EXTRUDER_MASS = {config.extruder_mass}  # grams (for analysis)
EXTRUDER_MOTOR = "{config.extruder_motor}"

# =============================================================================
# 5. CONTROL BOARD
# =============================================================================

PRIMARY_BOARD = "{primary_board_id}"
BOARD_IDS = {config.board_ids}
TOTAL_DRIVERS = {config.total_drivers}

# =============================================================================
# 6. TIER CONFIGURATION
# =============================================================================

BUILD_TIER = {config.tier}
Z_CONFIGURATION = "{config.z_configuration}"  # triple or belt
HAS_CANBUS = {config.has_canbus}

# =============================================================================
# 7. HOTEND (Reference defaults)
# =============================================================================

HOTEND_TYPE = "E3D_V6_CLONE"
GROOVEMOUNT_DIA = 16.0  # E3D V6 groove diameter
HEATER_BLOCK = "E3D_V6"

# =============================================================================
# 8. DERIVED VALUES (calculated from above)
# =============================================================================

# Frame dimensions (calculated by analysis tool)
# Run: python scripts/analyze.py to calculate these

FRAME_X = 0  # Set by analysis
FRAME_Y = 0  # Set by analysis
FRAME_Z = 0  # Set by analysis
X_SPAN = 0   # Smooth rod span (for sag calculation)

# =============================================================================
# 9. CAD PARAMETERS
# =============================================================================

# Tolerances for 3D printing
FIT_TOLERANCE = 0.2      # General fit tolerance
TIGHT_TOLERANCE = 0.1    # Tight fit (press-fit)
LOOSE_TOLERANCE = 0.4    # Loose fit (sliding)

# Printing parameters
MIN_WALL = 1.2           # Minimum wall thickness
MIN_FLOOR = 0.8          # Minimum floor thickness
'''

    return content


def save_config(config: BuildConfig, path: Optional[Path] = None) -> Path:
    """
    Generate and save config.py.

    Args:
        config: BuildConfig object
        path: Optional path (defaults to cad/config.py)

    Returns:
        Path where config was saved
    """
    if path is None:
        # Default to cad/config.py relative to project root
        scripts_dir = Path(__file__).parent.parent
        project_root = scripts_dir.parent
        path = project_root / "cad" / "config.py"

    content = generate_config(config)

    # Backup existing config
    if path.exists():
        backup_path = path.with_suffix(".py.backup")
        path.rename(backup_path)

    path.write_text(content)
    return path


def load_config(path: Optional[Path] = None) -> dict:
    """
    Load existing config.py as a dictionary.

    Args:
        path: Optional path (defaults to cad/config.py)

    Returns:
        Dictionary of config values
    """
    if path is None:
        scripts_dir = Path(__file__).parent.parent
        project_root = scripts_dir.parent
        path = project_root / "cad" / "config.py"

    if not path.exists():
        raise FileNotFoundError(f"Config not found: {path}")

    # Execute config.py and extract variables
    config_globals = {}
    exec(path.read_text(), config_globals)

    # Filter out dunder and module items
    return {
        k: v for k, v in config_globals.items()
        if not k.startswith("_") and not callable(v)
    }
