#!/usr/bin/env python3

"""
Amalgam Configuration Wizard
Interactive script to configure build parameters
"""

import sys
import os
from pathlib import Path


def print_header(title):
    print(f"\n{'=' * 60}")
    print(f"  {title}")
    print(f"{'=' * 60}\n")


def get_input(prompt, default):
    if default:
        response = input(f"{prompt} [{default}]: ").strip()
        return response if response else default
    return input(f"{prompt}: ").strip()


def get_yes_no(prompt, default=True):
    default_str = "Y/n" if default else "y/N"
    response = input(f"{prompt} [{default_str}]: ").strip().lower()
    if not response:
        return default
    return response in ["y", "yes", "true", "1"]


def configure_frame():
    print_header("Frame Configuration")

    print("Frame size (mm)")
    build_x = float(get_input("  X dimension (build volume width)", "300"))
    build_y = float(get_input("  Y dimension (build volume depth)", "300"))
    build_z = float(get_input("  Z dimension (build volume height)", "300"))

    print("\nM12 Skeleton rods")
    m12_dia = float(get_input("  Rod diameter (mm)", "12.0"))
    lumpy_factor = float(get_input("  Lumpy factor (extra clearance)", "0.5"))

    print("\nFrame margins (mm)")
    margin_x = float(get_input("  X margin", "120"))
    margin_y = float(get_input("  Y margin", "35"))
    margin_z = float(get_input("  Z margin", "30"))

    return {
        "BUILD_VOLUME_X": build_x,
        "BUILD_VOLUME_Y": build_y,
        "BUILD_VOLUME_Z": build_z,
        "M12_NOMINAL_DIA": m12_dia,
        "LUMPY_FACTOR": lumpy_factor,
        "FRAME_MARGIN_X": margin_x,
        "FRAME_MARGIN_Y": margin_y,
        "FRAME_MARGIN_Z": margin_z,
    }


def configure_extruder():
    print_header("Extruder Configuration")

    use_wade = get_yes_no("Use Wade Extruder?", True)

    if use_wade:
        print("\nWade Extruder settings")
        hobbed_bolt_dia = float(get_input("  Hobbed bolt diameter (mm)", "8.0"))
        filament_dia = float(get_input("  Filament diameter (mm)", "1.75"))
        gear_ratio = get_input("  Gear ratio (e.g., '47:11')", "47:11")
        motor_type = get_input("  Motor type", "NEMA17")
    else:
        hobbed_bolt_dia = 8.0
        filament_dia = 1.75
        gear_ratio = "1:1"
        motor_type = "NEMA17"

    print("\nHotend")
    hotend_type = get_input("  Hotend type", "E3D V6")
    groovemount_dia = float(get_input("  Groovemount diameter (mm)", "16.0"))

    return {
        "USE_WADE": use_wade,
        "HOBBED_BOLT_DIA": hobbed_bolt_dia,
        "FILAMENT_DIA": filament_dia,
        "GEAR_RATIO": gear_ratio,
        "EXTRUDER_MOTOR": motor_type,
        "HOTEND_TYPE": hotend_type,
        "GROOVEMOUNT_DIA": groovemount_dia,
    }


def configure_electronics():
    print_header("Electronics Configuration")

    print("Mainboard")
    mainboard_type = get_input("  Mainboard type", "MKS SKIPR")

    print("\nZ-Probe")
    use_bl_touch = get_yes_no("  Use BLTouch?", True)
    z_probe_offset_x = float(get_input("  Z-probe X offset (mm)", "35"))
    z_probe_offset_y = float(get_input("  Z-probe Y offset (mm)", "0"))

    print("\nMotors")
    use_canbus = get_yes_no("  Use CANbus for motors?", False)

    return {
        "MAINBOARD_TYPE": mainboard_type,
        "Z_PROBE_TYPE": "BLTouch" if use_bl_touch else "None",
        "Z_PROBE_OFFSET_X": z_probe_offset_x,
        "Z_PROBE_OFFSET_Y": z_probe_offset_y,
        "USE_CANBUS": use_canbus,
    }


def generate_config_file(config_data):
    """Generate config.py file from user input"""

    # Calculate frame dimensions
    x_overhang = 50.0 if config_data["USE_WADE"] else 25.0
    build_vol_x = config_data["BUILD_VOLUME_X"]
    build_vol_y = config_data["BUILD_VOLUME_Y"]
    build_vol_z = config_data["BUILD_VOLUME_Z"]

    skeleton_x = build_vol_x + config_data["FRAME_MARGIN_X"]
    skeleton_y = build_vol_y + config_data["FRAME_MARGIN_Y"]
    skeleton_z = build_vol_z + config_data["FRAME_MARGIN_Z"]

    z_travel = skeleton_z - 25 - 15  # Bottom + Top clearance

    config_content = f'''"""
Amalgam Configuration
Generated by configure.py

This file contains all configuration parameters for the Amalgam 3D printer.
Edit manually or run ./configure.py for an interactive wizard.
"""

# --- DONOR & TRANSPARENCY ---
# Options: "PRUSA_CLONE", "ENDER_3", "SCAVENGED"
DONOR_TYPE = "ENDER_3"

# --- THE SKELETON (M12 RODS) ---
M12_NOMINAL_DIA = {config_data["M12_NOMINAL_DIA"]}
# Set 0.2 for Zinc, 0.5+ for Galvanized (The "Lumpy Factor")
LUMPY_FACTOR = {config_data["LUMPY_FACTOR"]}
M12_FIT_DIA = M12_NOMINAL_DIA + LUMPY_FACTOR

# --- MOTION FORK (SMOOTH RODS) ---
# 8.0 for salvage, 10.0 for "Neo" Standard
SMOOTH_ROD_DIA = 10.0
BEARING_TYPE = "LM10UU" if SMOOTH_ROD_DIA == 10.0 else "LM8UU"

# --- TIER DEFINITIONS ---
TRIPLE_Z = True  # True = Independent 3-point Z-Tilt
EXTRUDER_TYPE = "WADE"  # The Signature 13:43 Geared Torque Monster
HOTEND_DONOR = "ENDER_MK8"

# --- BUILD VOLUME ---
BUILD_VOLUME = {{"X": {build_vol_x}, "Y": {build_vol_y}, "Z": {build_vol_z}}}

# --- DYNAMIC FRAME CALCULATIONS ---
# Greg's Wade requires a significant "Gear Overhang" on the X-axis
X_OVERHANG = {x_overhang}

# --- FRAME GEOMETRY (Amalgam M12 Frame) ---
# Frame has 8 vertical rods (4 front, 4 back) with horizontal top/bottom rods

# M12 SKELETON (Reduced height from 80 to 50 for efficiency)
SKELETON_X = {skeleton_x}
SKELETON_Y = {skeleton_y}
SKELETON_Z = {skeleton_z}

# Vertical Rod Positions
FRONT_LEFT_V = True  # VFL
FRONT_CENTER_V = True  # VFC (optional center rod)
FRONT_RIGHT_V = True  # VFR
BACK_LEFT_V = True  # VBL
BACK_CENTER_V = True  # VBC
BACK_RIGHT_V = True  # VBR

# --- Z-SYSTEM MOUNTING ---
TRIPLE_Z = True
Z_MOUNT_PATTERN = (
    "FRONT_CORNERS_BACK_BOTTOM"  # Front L+R integrated, Back Center on bottom rod
)

# Corner Count and Types
BOTTOM_CORNERS = 4  # 2 Z-mount + 2 standard
TOP_CORNERS = 4  # All standard (gantry)
TOTAL_CORNERS = 8

# Z-Motor Locations
Z1_LOCATION = "front_left_corner"  # Integrated into Corner 1
Z2_LOCATION = "front_right_corner"  # Integrated into Corner 2
Z3_LOCATION = "back_center_rod"  # Separate Z-puck on back bottom rod

# Corner Types
FRONT_LEFT_CORNER = "Z_MOUNT_INTEGRATED"
FRONT_RIGHT_CORNER = "Z_MOUNT_INTEGRATED"
BACK_LEFT_CORNER = "STANDARD"
BACK_RIGHT_CORNER = "STANDARD"

# Z-Clearances
BOTTOM_Z_CLEARANCE = 25  # Bed + spider + nut clearance from bottom frame
TOP_Z_CLEARANCE = 15  # Bed to gantry clearance
Z_TRAVEL_MAX = {z_travel}mm travel

# --- SPIDER BED SUPPORT ---
SPIDER_ARM_LENGTH = 150
SPIDER_HUB_SIZE = 120
SPIDER_BOLT_PATTERN = "M6"
SPIDER_INTERLOCK = True
SPIDER_LEADSCREW_SPACING = 40  # Distance between leadscrews for hub

# --- EXTRUDER (from configure.py) ---
USE_WADE = {config_data["USE_WADE"]}
HOBBED_BOLT_DIA = {config_data["HOBBED_BOLT_DIA"]}
FILAMENT_DIA = {config_data["FILAMENT_DIA"]}
GEAR_RATIO = "{config_data["GEAR_RATIO"]}"
EXTRUDER_MOTOR = "{config_data["EXTRUDER_MOTOR"]}"
HOTEND_TYPE = "{config_data["HOTEND_TYPE"]}"
GROOVEMOUNT_DIA = {config_data["GROOVEMOUNT_DIA"]}

# --- ELECTRONICS (from configure.py) ---
MAINBOARD_TYPE = "{config_data["MAINBOARD_TYPE"]}"
Z_PROBE_TYPE = "{config_data["Z_PROBE_TYPE"]}"
Z_PROBE_OFFSET_X = {config_data["Z_PROBE_OFFSET_X"]}
Z_PROBE_OFFSET_Y = {config_data["Z_PROBE_OFFSET_Y"]}
USE_CANBUS = {config_data["USE_CANBUS"]}

# --- UTILITIES ---
def print_config_summary():
    """Print configuration summary"""
    print(f"--- Amalgam Configuration: {{DONOR_TYPE}} Path ---")
    if DONOR_TYPE == "ENDER_3":
        print(
            f"!!! MOTION GAP: Ender rollers incompatible. Buy 6x {{SMOOTH_ROD_DIA}}mm rods."
        )
    print(f"Frame Dimensions: {{SKELETON_X}} x {{SKELETON_Y}} x {{SKELETON_Z}}")
    print(f"Z-Travel: {{Z_TRAVEL_MAX}}mm (Frame: {{SKELETON_Z}}mm)")
    print(f"Z-Motors: {{Z1_LOCATION}}, {{Z2_LOCATION}}, {{Z3_LOCATION}}")
    print(f"Extruder: {{EXTRUDER_TYPE}} ({{GEAR_RATIO}}) with {{HOTEND_TYPE}}")
    print(f"Mainboard: {{MAINBOARD_TYPE}}, Z-Probe: {{Z_PROBE_TYPE}}")
    print(
        f"Parts: {{BOTTOM_CORNERS}} bottom corners + {{TOP_CORNERS}} top corners = {{TOTAL_CORNERS}} total"
    )


if __name__ == "__main__":
    print_config_summary()
'''

    return config_content


def main():
    print_header("Amalgam Configuration Wizard")
    print("This wizard will guide you through configuring your printer.")
    print("Answer the questions or press Enter to use default values.\n")

    config_data = {}
    config_data.update(configure_frame())
    config_data.update(configure_extruder())
    config_data.update(configure_electronics())

    print_header("Configuration Summary")

    print("Build Volume:")
    print(f"  X: {config_data['BUILD_VOLUME_X']}mm")
    print(f"  Y: {config_data['BUILD_VOLUME_Y']}mm")
    print(f"  Z: {config_data['BUILD_VOLUME_Z']}mm")

    print("\nFrame:")
    print(
        f"  Skeleton size: {config_data['BUILD_VOLUME_X'] + config_data['FRAME_MARGIN_X']}x{config_data['BUILD_VOLUME_Y'] + config_data['FRAME_MARGIN_Y']}x{config_data['BUILD_VOLUME_Z'] + config_data['FRAME_MARGIN_Z']}mm"
    )
    print(
        f"  M12 rods: {config_data['M12_NOMINAL_DIA']}mm (fit: {config_data['M12_NOMINAL_DIA'] + config_data['LUMPY_FACTOR']}mm)"
    )

    print("\nExtruder:")
    print(f"  Wade Extruder: {config_data['USE_WADE']}")
    print(f"  Hotend: {config_data['HOTEND_TYPE']}")
    print(f"  Filament: {config_data['FILAMENT_DIA']}mm")

    print("\nElectronics:")
    print(f"  Mainboard: {config_data['MAINBOARD_TYPE']}")
    print(f"  Z-Probe: {config_data['Z_PROBE_TYPE']}")
    print(f"  CANbus: {config_data['USE_CANBUS']}")

    save = get_yes_no("\nSave this configuration?", True)

    if save:
        config_path = Path("config.py")
        config_content = generate_config_file(config_data)

        backup_path = None
        if config_path.exists():
            backup = get_yes_no(f"Backup existing {config_path}?", True)
            if backup:
                import shutil

                backup_path = config_path.with_suffix(".py.backup")
                shutil.copy(config_path, backup_path)
                print(f"  Backed up to: {backup_path}")

        with open(config_path, "w") as f:
            f.write(config_content)

        print(f"\n✓ Configuration saved to {config_path}")
        if backup_path:
            print(f"  Backup: {backup_path}")
        print("\nYou can now run: ./build.sh")
    else:
        print("\nConfiguration not saved.")

    build_now = get_yes_no("\nBuild all parts now?", False)
    if build_now:
        import subprocess

        subprocess.run(["./build.sh", "build_all"])


if __name__ == "__main__":
    main()
