"""
Amalgam Configuration
Generated by wizard.py

Tier: 3 (Reference Spec)
"""

# =============================================================================
# 1. BUILD VOLUME
# =============================================================================

BUILD_VOLUME = {
    "x": 235,
    "y": 235,
    "z": 250,
}

# =============================================================================
# 2. FRAME SKELETON (M10 Rods)
# =============================================================================

# Threaded rods (frame structure)
M10_NOMINAL_DIA = 10.0
LUMPY_FACTOR = 0.5  # Tolerance for rod variation (0.2 zinc, 0.5+ galvanized)
M10_FIT_DIA = M10_NOMINAL_DIA + LUMPY_FACTOR

# Smooth rods (linear motion)
SMOOTH_ROD_DIA = 10.0
SMOOTH_ROD_FIT = SMOOTH_ROD_DIA + 0.1  # Tight fit for linear bearings

# =============================================================================
# 3. BED CONFIGURATION
# =============================================================================

BED_SIZE_X = 235
BED_SIZE_Y = 235
BED_ID = "ENDER3_BED"

# =============================================================================
# 4. EXTRUDER
# =============================================================================

EXTRUDER_TYPE = "PITAN"
EXTRUDER_MASS = 280  # grams (for analysis)
EXTRUDER_MOTOR = "STANDARD"

# =============================================================================
# 5. CONTROL BOARD
# =============================================================================

PRIMARY_BOARD = "MKS_SKIPR"
BOARD_IDS = ['MKS_SKIPR']
TOTAL_DRIVERS = 6

# =============================================================================
# 6. TIER CONFIGURATION
# =============================================================================

BUILD_TIER = 3
Z_CONFIGURATION = "triple"  # triple or belt
HAS_CANBUS = True

# =============================================================================
# 7. HOTEND (Reference defaults)
# =============================================================================

HOTEND_TYPE = "E3D_V6_CLONE"
GROOVEMOUNT_DIA = 16.0  # E3D V6 groove diameter
HEATER_BLOCK = "E3D_V6"

# =============================================================================
# 8. DERIVED VALUES (calculated from above)
# =============================================================================

# Frame dimensions (calculated by analysis tool)
# These will be updated when you run: python scripts/analyze.py

FRAME_X = 0  # Set by analysis
FRAME_Y = 0  # Set by analysis
FRAME_Z = 0  # Set by analysis
X_SPAN = 0   # Smooth rod span (for sag calculation)

# =============================================================================
# 9. CAD PARAMETERS
# =============================================================================

# Tolerances for 3D printing
FIT_TOLERANCE = 0.2      # General fit tolerance
TIGHT_TOLERANCE = 0.1    # Tight fit (press-fit)
LOOSE_TOLERANCE = 0.4    # Loose fit (sliding)

# Printing parameters
MIN_WALL = 1.2           # Minimum wall thickness
MIN_FLOOR = 0.8          # Minimum floor thickness

# =============================================================================
# 10. EXPORT SETTINGS
# =============================================================================

# Default export format: stl, step, 3mf, brep, gltf, or all
EXPORT_FORMAT = "stl"

# Generate technical drawings (orthographic projections as SVG/PDF)
EXPORT_DRAWINGS = False

# =============================================================================
# 11. BRAND & COSMETICS
# =============================================================================

# Official palette (hex). Feeds into exports, docs, and website.
BRAND_BODY_COLOR = "#4A4A4A"       # Dark Grey — printed parts
BRAND_ACCENT_COLOR = "#FFFFFF"     # White — logo pad / raised details
BRAND_BASE_COLOR = "#1A1A1A"       # Near-Black — MDF base, extrusions

# Logo pad on printed parts (raised 0.5mm for filament-swap color change)
LOGO_PAD_ENABLED = True            # Set False for plain parts
LOGO_PAD_DIAMETER = 18.0           # mm, across flats
LOGO_PAD_HEIGHT = 0.5              # mm raised above surface

# Texture (slicer recommendation, not enforced by geometry)
FUZZY_SKIN_RECOMMENDED = True
FUZZY_SKIN_POINT_DISTANCE = 0.3   # mm
FUZZY_SKIN_THICKNESS = 0.2        # mm
